packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@eslint/compat": 1.2.0
  "@ianvs/prettier-plugin-sort-imports": 4.3.1 # trying it out to see if it's better than the deprecated trivago one (@trivago/prettier-plugin-sort-imports, ~> 1 year since last publish)
  "@next/eslint-plugin-next": 14.2.14
  "@types/eslint-config-prettier": 6.11.3
  eslint: 9.12.0
  eslint-config-prettier: 9.1.0
  eslint-plugin-import: 2.31.0
  eslint-plugin-jsx-a11y: 6.10.0
  eslint-plugin-prettier: 5.1.3
  eslint-plugin-react: 7.37.1
  eslint-plugin-react-hooks: 5.1.0
  eslint-plugin-storybook: 0.11.1
  eslint-plugin-turbo: 2.3.3
  prettier: 3.3.3
  prettier-plugin-tailwindcss: 0.6.8
  typescript: 5.6.2
  typescript-eslint: 8.8.1